### ISSUE TITLE
drag and drop mobile support

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/Obsidian-ZettelFlow#32]
We are keeping working on improve the use of DnD. On mobile its not working right now

**Comment by RafaelGB** [comment]
fixed using a parent with a custom property

```css
.zettelkasten-flow__sortable {
  /* Support for mobile Drag & Drop */
  touch-action: none;
}
```
